import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { core } from './lib/core'
import type { MemoryStatus, PagerResult, ProcessInfo, SystemStatus } from './types'
import './styles.css'

const pages = [['dashboard', 'Overview'], ['processes', 'Processes'], ['memory', 'Memory'], ['paging', 'Paging Lab'], ['activity', 'Activity'], ['policies', 'Policies'], ['settings', 'Settings']]
function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span> }
function Metric({ label, value, detail, tone }: { label: string; value: React.ReactNode; detail: string; tone?: string }) { return <div className="metric"><span>{label}</span><strong className={tone?.toLowerCase()}>{value}</strong><small>{detail}</small></div> }

function App() {
  const [page, setPage] = useState('dashboard'); const [status, setStatus] = useState<SystemStatus | null>(null); const [memory, setMemory] = useState<MemoryStatus | null>(null); const [history, setHistory] = useState(''); const [processes, setProcesses] = useState<ProcessInfo[]>([]); const [cpuHistory, setCpuHistory] = useState<number[]>([]); const [connected, setConnected] = useState(false); const [error, setError] = useState(''); const [dryRun, setDryRun] = useState(false)
  useEffect(() => { let active = true; const poll = async () => { try { const [s, m, p, h] = await Promise.all([core.status(), core.memory(), core.processes(), core.history()]); if (active) { setStatus(s); setMemory(m); setProcesses(p); setHistory(h); setCpuHistory(old => [...old, s.cpu_percent].slice(-60)); setConnected(true); setError('') } } catch (e) { if (active) { setConnected(false); setError(String(e)) } } }; poll(); const timer = setInterval(poll, 2500); return () => { active = false; clearInterval(timer) } }, [])
  return <div className="shell"><aside><div className="brand"><div className="brand-mark">A</div><div><strong>AutoNicer</strong><small>Linux control plane</small></div></div><nav>{pages.map(([id, label]) => <button className={page === id ? 'active' : ''} onClick={() => setPage(id)} key={id}>{label}</button>)}</nav><div className="side-bottom"><div className="connection"><i className={connected ? 'online' : ''} /><div><b>{connected ? 'Core connected' : 'Core unavailable'}</b><small>{connected ? 'Fresh OS data' : 'Check the C core'}</small></div></div><small className="version">AutoNicer 1.0 · Linux</small></div></aside><main><header><div><p className="eyebrow">LOAD-AWARE BACKGROUND JOB CONTROLLER</p><h1>{pages.find(p => p[0] === page)?.[1]}</h1></div><div className="header-actions"><Badge tone={dryRun ? 'amber' : 'green'}>{dryRun ? 'DRY RUN' : 'LIVE CONTROL'}</Badge><button className="outline" onClick={() => setDryRun(v => !v)}>{dryRun ? 'Enable live' : 'Preview only'}</button></div></header>{error && <div className="error">Core unavailable: {error}</div>}{page === 'dashboard' && <Dashboard status={status} history={history} cpuHistory={cpuHistory} processes={processes} />}{page === 'processes' && <Processes processes={processes} />}{page === 'memory' && <MemoryPage memory={memory} />}{page === 'paging' && <PagingLab />}{page === 'activity' && <section className="panel activity-page"><h2>Controller activity</h2><pre className="history-full">{history || 'No activity yet.'}</pre></section>}{page === 'policies' && <Policies />}{page === 'settings' && <Settings connected={connected} />}</main></div>
}

function Dashboard({ status, history, cpuHistory, processes }: { status: SystemStatus | null; history: string; cpuHistory: number[]; processes: ProcessInfo[] }) { const cpu = status?.cpu_percent ?? 0; const state = status?.load_state ?? 'NORMAL'; const points = (cpuHistory.length ? cpuHistory : [cpu]).map((v, i, a) => `${a.length < 2 ? 0 : i * 800 / (a.length - 1)},${210 - v * 1.9}`).join(' '); return <><section className="metrics"><Metric label="CPU utilization" value={`${cpu.toFixed(1)}%`} detail="latest /proc/stat sample" tone={state} /><Metric label="Controller state" value={state} detail="independent of memory state" tone={state} /><Metric label="Registered processes" value={processes.length} detail="current registry" /><Metric label="Protected" value={processes.filter(p => p.protected).length} detail="excluded automatically" /></section><section className="grid-main"><div className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">LIVE OS TELEMETRY</p><h2>CPU utilization</h2></div><Badge tone="green">REAL DATA</Badge></div><div className="chart"><div className="threshold critical">90%</div><div className="threshold high">80%</div><svg viewBox="0 0 800 220" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="3" /></svg><div className="axis"><span>{cpuHistory.length} samples</span><span>2.5s polling</span><span>Now</span></div></div></div><div className="panel decision"><div className="panel-head"><div><p className="eyebrow">POLICY OUTPUT</p><h2>Current decision</h2></div><Badge tone={state === 'NORMAL' ? 'green' : 'amber'}>{state}</Badge></div><div className="empty"><b>{state === 'NORMAL' ? 'No intervention required' : 'Safe candidate evaluation active'}</b><span>Decisions remain in the C core.</span></div></div></section><section className="panel activity-preview"><p className="eyebrow">AUDIT TRAIL</p><h2>Recent activity</h2><pre>{history.split('\n').filter(Boolean).slice(-4).join('\n') || 'No actions yet.'}</pre></section></> }

function Processes({ processes }: { processes: ProcessInfo[] }) { return <section className="panel process-panel"><div className="panel-head"><div><p className="eyebrow">LIVE PROCESS DATA</p><h2>Registered processes</h2></div><Badge>{processes.length} processes</Badge></div><div className="table-wrap"><table><thead><tr><th>PID</th><th>Process</th><th>CPU</th><th>RSS</th><th>Swap</th><th>Major faults/s</th><th>Class</th><th>Protection</th></tr></thead><tbody>{processes.map(p => <tr key={p.pid}><td className="mono">{p.pid}</td><td><b>{p.name}</b></td><td className="mono">{p.cpuPercent.toFixed(1)}%</td><td className="mono">{(p.rssKb / 1024).toFixed(1)}M</td><td className="mono">{(p.swapKb / 1024).toFixed(1)}M</td><td className="mono">{p.majorFaultsPerSecond.toFixed(1)}</td><td><Badge tone={p.classification === 'BACKGROUND' ? 'blue' : p.classification === 'CRITICAL' ? 'red' : 'neutral'}>{p.classification}</Badge></td><td>{p.protected ? <Badge tone="purple">PROTECTED</Badge> : '—'}</td></tr>)}</tbody></table>{!processes.length && <div className="empty table-empty"><b>No registered processes</b><span>Register a process through the C CLI.</span></div>}</div></section> }

function MemoryPage({ memory }: { memory: MemoryStatus | null }) { if (!memory) return <section className="panel empty-page"><b>Waiting for fresh OS memory data</b><span>No decisions are made until the core returns a valid sample.</span></section>; const age = Math.max(0, Math.floor(Date.now() / 1000 - memory.timestamp)); return <><section className="metrics"><Metric label="Memory pressure" value={memory.memory_state} detail="from /proc/meminfo" tone={memory.memory_state} /><Metric label="Available RAM" value={`${(memory.available_kb / 1024).toFixed(0)} MB`} detail={`${memory.available_percent.toFixed(1)}% available`} /><Metric label="Swap used" value={`${(memory.swap_used_kb / 1024).toFixed(0)} MB`} detail={`${(memory.swap_total_kb / 1024).toFixed(0)} MB total`} /><Metric label="Major faults/s" value={memory.major_faults_per_second.toFixed(1)} detail="/proc/vmstat delta" /></section><section className="panel memory-panel"><div className="panel-head"><div><p className="eyebrow">LIVE LINUX MEMORY</p><h2>Pressure telemetry</h2></div><Badge tone={age < 8 ? 'green' : 'red'}>{age < 8 ? `FRESH · ${age}s` : `STALE · ${age}s`}</Badge></div><div className="memory-bars"><div><span>Available RAM</span><b>{memory.available_percent.toFixed(1)}%</b><i><em style={{ width: `${memory.available_percent}%` }} /></i></div><div><span>Swap used</span><b>{memory.swap_total_kb ? (memory.swap_used_kb / memory.swap_total_kb * 100).toFixed(1) : '0.0'}%</b><i><em className="amber-fill" style={{ width: `${memory.swap_total_kb ? memory.swap_used_kb / memory.swap_total_kb * 100 : 0}%` }} /></i></div></div><p className="sample-time">Latest successful OS sample: {new Date(memory.timestamp * 1000).toLocaleTimeString()}</p></section><section className="panel counter-grid"><Metric label="Minor faults/s" value={memory.minor_faults_per_second.toFixed(1)} detail="/proc/vmstat" /><Metric label="Swap in/s" value={memory.swap_in_per_second.toFixed(1)} detail="/proc/vmstat" /><Metric label="Swap out/s" value={memory.swap_out_per_second.toFixed(1)} detail="/proc/vmstat" /><Metric label="PSI" value="available through core" detail="optional /proc/pressure/memory" /></section></> }

function PagingLab() { const [algorithm, setAlgorithm] = useState('clock'); const [frames, setFrames] = useState(4); const [reference, setReference] = useState('7,0,1,2,0,3,0,4'); const [result, setResult] = useState<PagerResult | null>(null); const [step, setStep] = useState(0); const [error, setError] = useState(''); const run = async () => { try { setResult(await core.pager(algorithm, frames, reference)); setStep(0); setError('') } catch (e) { setError(String(e)) } }; const current = result?.steps[step]; return <section className="panel paging-lab"><div className="panel-head"><div><p className="eyebrow">EDUCATIONAL SIMULATION</p><h2>Paging laboratory</h2></div><Badge tone="blue">NO LINUX PAGES MODIFIED</Badge></div><div className="lab-controls"><label>Algorithm<select value={algorithm} onChange={e => setAlgorithm(e.target.value)}><option value="clock">Clock</option><option value="fifo">FIFO</option><option value="lru">LRU</option></select></label><label>Frames<input type="number" min="1" max="128" value={frames} onChange={e => setFrames(Number(e.target.value))} /></label><label className="reference-input">Reference string<input value={reference} onChange={e => setReference(e.target.value)} /></label><button className="run-button" onClick={run}>Run simulation</button></div>{error && <div className="error">{error}</div>}{result && <><div className="lab-stats"><Metric label="Hits" value={result.hits} detail="references found" /><Metric label="Faults" value={result.faults} detail="pages loaded" tone="HIGH" /><Metric label="Evictions" value={result.evictions} detail="victims selected" /><Metric label="Write-backs" value={result.writeBacks} detail="dirty pages" /></div><div className="step-bar"><b>Reference {step + 1} / {result.steps.length}</b><span>{current?.fault ? 'PAGE FAULT' : 'PAGE HIT'} · page {current?.reference}</span><button disabled={!step} onClick={() => setStep(step - 1)}>Previous</button><button disabled={step >= result.steps.length - 1} onClick={() => setStep(step + 1)}>Next</button></div><div className="frame-table"><h3>Physical frame table</h3>{current?.frames.map((page, index) => <div className="frame-row" key={index}><span>Frame {index}</span><b>{page < 0 ? 'empty' : `Page ${page}`}</b><Badge tone={current.frame === index ? 'blue' : 'neutral'}>{current.frame === index ? 'SELECTED' : '-'}</Badge></div>)}</div></>}</section> }
function Policies() { return <section className="panel policies"><p className="eyebrow">CONTROLLER POLICY</p><h2>CPU and memory signals</h2><div className="policy-list"><div><b>Memory state</b><span>Available RAM thresholds are read from the core configuration.</span></div><div><b>Paging lab</b><span>Simulation is isolated from live Linux memory management.</span></div><div><b>Safety</b><span>Only registered BACKGROUND processes can be candidates.</span></div><div><b>Missing data</b><span>Stale or invalid OS samples do not produce decisions.</span></div></div></section> }
function Settings({ connected }: { connected: boolean }) { return <section className="panel settings"><p className="eyebrow">APPLICATION</p><h2>Settings</h2><div className="setting"><div><b>Core connection</b><span>Approved C core bridge</span></div><Badge tone={connected ? 'green' : 'red'}>{connected ? 'CONNECTED' : 'DISCONNECTED'}</Badge></div><div className="callout">Live Linux telemetry and memory decisions remain authoritative in the C core.</div></section> }
createRoot(document.getElementById('root')!).render(<App />)
