import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {core} from './lib/core'
import type {Classification,LoadState,ProcessInfo,SystemStatus} from './types'
import './styles.css'

const nav=[['dashboard','Overview'],['processes','Processes'],['activity','Activity'],['policies','Policies'],['settings','Settings']]
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function App(){const [page,setPage]=useState('dashboard');const [status,setStatus]=useState<SystemStatus|null>(null);const [processes,setProcesses]=useState<ProcessInfo[]>([]);const [history,setHistory]=useState('');const [connected,setConnected]=useState(false);const [dryRun,setDryRun]=useState(false);const [selected,setSelected]=useState<ProcessInfo|null>(null);const [search,setSearch]=useState('');const [sort,setSort]=useState<'cpu'|'pid'>('cpu');const [error,setError]=useState('');
 useEffect(()=>{let live=true;const poll=async()=>{try{const [s,p,h]=await Promise.all([core.status(),core.processes(),core.history()]);if(live){setStatus(s);setProcesses(p);setHistory(h);setConnected(true);setError('')}}catch(e){if(live){setConnected(false);setError(String(e))}}};poll();const id=setInterval(poll,2500);return()=>{live=false;clearInterval(id)}},[])
 const run=async(command:string,pid:number,classification?:string)=>{try{await core.command(command,pid,classification);const p=await core.processes();setProcesses(p);setSelected(p.find(x=>x.pid===pid)||null)}catch(e){setError(String(e))}}
 const filtered=processes.filter(p=>`${p.pid} ${p.name}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='cpu'?b.cpuPercent-a.cpuPercent:a.pid-b.pid)
 return <div className="shell"><aside><div className="brand"><div className="brand-mark">A</div><div><strong>AutoNicer</strong><small>Linux control plane</small></div></div><nav>{nav.map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><span>{['◈','▦','≡','◇','⚙'][nav.findIndex(x=>x[0]===id)]}</span>{label}</button>)}</nav><div className="side-bottom"><div className="connection"><i className={connected?'online':''}/><div><b>{connected?'Core connected':'Core unavailable'}</b><small>{connected?'Live data':'Check the C core'}</small></div></div><small className="version">AutoNicer 1.0 · Linux</small></div></aside><main><header><div><p className="eyebrow">LOAD-AWARE BACKGROUND JOB CONTROLLER</p><h1>{page==='dashboard'?'System overview':nav.find(x=>x[0]===page)?.[1]}</h1></div><div className="header-actions"><Badge tone={dryRun?'amber':'green'}>{dryRun?'DRY RUN':'LIVE CONTROL'}</Badge><button className="outline" onClick={()=>setDryRun(!dryRun)}>{dryRun?'Enable live':'Preview only'}</button></div></header>{error&&<div className="error">Core unavailable: {error}</div>}{page==='dashboard'&&<Dashboard status={status} processes={processes} history={history} onOpen={()=>setPage('processes')}/>} {page==='processes'&&<Processes items={filtered} search={search} setSearch={setSearch} sort={sort} setSort={setSort} selected={selected} setSelected={setSelected} run={run}/>} {page==='activity'&&<Activity history={history}/>} {page==='policies'&&<Policies/>} {page==='settings'&&<Settings connected={connected}/>}</main></div>}

function Dashboard({status,processes,history,onOpen}:{status:SystemStatus|null;processes:ProcessInfo[];history:string;onOpen:()=>void}){const cpu=status?.cpu_percent??0;const background=processes.filter(p=>p.classification==='BACKGROUND').length;const protectedCount=processes.filter(p=>p.protected).length;const state=status?.load_state||'NORMAL';return <><section className="metrics"><Metric label="CPU utilization" value={`${cpu.toFixed(1)}%`} detail="system aggregate" tone={state}/><Metric label="Controller state" value={state} detail={state==='NORMAL'?'No intervention required':'Policy evaluation active'} tone={state}/><Metric label="Registered processes" value={processes.length} detail="known to the core"/><Metric label="Protected" value={protectedCount} detail={`${background} background eligible`}/></section><section className="grid-main"><div className="panel chart-panel"><div className="panel-head"><div><p className="eyebrow">LIVE TELEMETRY</p><h2>CPU utilization</h2></div><Badge tone={state==='NORMAL'?'green':'amber'}>{state}</Badge></div><div className="chart"><div className="threshold critical">90%</div><div className="threshold high">80%</div><svg viewBox="0 0 800 220" preserveAspectRatio="none"><polyline points="0,180 80,165 160,174 240,130 320,142 400,92 480,108 560,72 640,98 720,54 800,76" fill="none" stroke="currentColor" strokeWidth="3"/></svg><div className="axis"><span>60 sec ago</span><span>30 sec</span><span>Now</span></div></div></div><div className="panel decision"><div className="panel-head"><div><p className="eyebrow">POLICY OUTPUT</p><h2>AutoNicer decision</h2></div><span className="decision-dot"/></div>{state==='NORMAL'?<div className="empty"><b>System is within range</b><span>No intervention is required.</span></div>:<div className="decision-flow"><div className="flow-step done">High CPU detected</div><div className="flow-line"/><div className="flow-step active">Evaluate safe background process</div><div className="flow-line"/><div className="flow-step">Renice first, then recheck</div></div>}</div></section><section className="panel activity-preview"><div className="panel-head"><div><p className="eyebrow">AUDIT TRAIL</p><h2>Recent activity</h2></div><button className="text-button" onClick={()=>onOpen()}>View processes →</button></div>{history?<pre>{history.split('\n').filter(Boolean).slice(-4).join('\n')}</pre>:<div className="empty"><b>No actions yet</b><span>Meaningful controller decisions will appear here.</span></div>}</section></>}
function Metric({label,value,detail,tone}:{label:string;value:React.ReactNode;detail:string;tone?:string}){return <div className="metric"><span>{label}</span><strong className={tone?.toLowerCase()}>{value}</strong><small>{detail}</small></div>}
function Processes({items,search,setSearch,sort,setSort,selected,setSelected,run}:{items:ProcessInfo[];search:string;setSearch:(x:string)=>void;sort:string;setSort:(x:'cpu'|'pid')=>void;selected:ProcessInfo|null;setSelected:(p:ProcessInfo|null)=>void;run:(c:string,p:number,k?:string)=>void}){return <div className="process-layout"><section className="panel process-panel"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search PID or process name"/><button className="outline" onClick={()=>setSort(sort==='cpu'?'pid':'cpu')}>Sort: {sort==='cpu'?'CPU':'PID'} ↕</button></div><div className="table-wrap"><table><thead><tr><th>PID</th><th>Process</th><th>CPU</th><th>Nice</th><th>State</th><th>Class</th><th>Protection</th></tr></thead><tbody>{items.map(p=><tr className={selected?.pid===p.pid?'selected':''} onClick={()=>setSelected(p)} key={p.pid}><td className="mono">{p.pid}</td><td><b>{p.name}</b><small className="row-sub">{p.paused?'Paused by AutoNicer':''}</small></td><td className="mono">{p.cpuPercent.toFixed(1)}%</td><td className="mono">{p.nice}</td><td><span className="state-dot"/> {p.state}</td><td><Badge tone={p.classification==='BACKGROUND'?'blue':p.classification==='CRITICAL'?'red':'neutral'}>{p.classification}</Badge></td><td>{p.protected?<Badge tone="purple">PROTECTED</Badge>:'—'}</td></tr>)}</tbody></table>{!items.length&&<div className="empty table-empty"><b>No registered processes</b><span>Classify a process as BACKGROUND in the CLI to manage it.</span></div>}</div></section>{selected&&<Details process={selected} close={()=>setSelected(null)} run={run}/>}</div>}
function Details({process:p,close,run}:{process:ProcessInfo;close:()=>void;run:(c:string,p:number,k?:string)=>void}){return <aside className="drawer"><div className="drawer-head"><div><p className="eyebrow">PROCESS DETAIL</p><h2>{p.name}</h2><span className="mono">PID {p.pid}</span></div><button className="icon-button" onClick={close}>×</button></div><div className="detail-stats"><Metric label="CPU" value={`${p.cpuPercent.toFixed(1)}%`} detail="recent activity"/><Metric label="Nice" value={p.nice} detail="scheduling preference"/></div><div className="detail-row"><span>Classification</span><Badge tone={p.classification==='BACKGROUND'?'blue':'neutral'}>{p.classification}</Badge></div><div className="detail-row"><span>Protection</span>{p.protected?<Badge tone="purple">Protected</Badge>:<span>Not protected</span>}</div><div className="detail-actions"><h3>Controls</h3><div className="button-grid"><button onClick={()=>run('classify',p.pid,'normal')}>Mark normal</button><button onClick={()=>run('classify',p.pid,'background')}>Mark background</button><button onClick={()=>run('classify',p.pid,'critical')}>Mark critical</button><button onClick={()=>run(p.protected?'unprotect':'protect',p.pid)}>{p.protected?'Remove protection':'Protect process'}</button><button disabled={!p.priorityChanged} onClick={()=>run('restore',p.pid)}>Restore priority</button><button disabled={!p.paused} onClick={()=>run('resume',p.pid)}>Resume process</button></div></div><p className="safety-note">Actions are requests to the C core. Linux identity, ownership, permissions, and safety policy are checked there before any change.</p></aside>}
function Activity({history}:{history:string}){return <section className="panel activity-page"><div className="panel-head"><div><p className="eyebrow">AUDIT TRAIL</p><h2>Controller activity</h2></div><Badge>{history?`${history.split('\n').filter(Boolean).length} events`:'No events'}</Badge></div>{history?<pre className="history-full">{history}</pre>:<div className="empty"><b>No AutoNicer actions yet</b><span>Start monitoring to see confirmed decisions and system events.</span></div>}</section>}
function Policies(){return <section className="panel policies"><div className="panel-head"><div><p className="eyebrow">CONTROLLER POLICY</p><h2>How AutoNicer responds</h2></div><Badge tone="green">Core defaults</Badge></div><div className="policy-list"><div><b>High CPU threshold</b><span>80% · sustained before evaluation</span></div><div><b>Critical CPU threshold</b><span>90% · pause is last resort</span></div><div><b>Priority adjustment</b><span>+5 nice · maximum 19</span></div><div><b>Cooldown</b><span>8 seconds between interventions</span></div><div><b>Automatic pause</b><span><Badge tone="green">OFF</Badge> confirmation remains required</span></div></div><div className="callout">Only explicitly registered BACKGROUND processes can be managed. NORMAL, CRITICAL, and PROTECTED processes remain untouched.</div></section>}
function Settings({connected}:{connected:boolean}){return <section className="panel settings"><div className="panel-head"><div><p className="eyebrow">APPLICATION</p><h2>Settings</h2></div></div><div className="setting"><div><b>Core connection</b><span>The desktop bridge invokes the approved AutoNicer C executable.</span></div><Badge tone={connected?'green':'red'}>{connected?'CONNECTED':'DISCONNECTED'}</Badge></div><div className="setting"><div><b>Operating system</b><span>Linux process controls are provided by the C core.</span></div><Badge>LINUX</Badge></div><div className="callout">The C engine remains authoritative. This interface never executes arbitrary shell commands or sends process signals directly.</div></section>}
createRoot(document.getElementById('root')!).render(<App/>)
