#include "controller.h"
#include "process.h"
#include "monitor.h"
#include "logger.h"
#include <sys/resource.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <time.h>

int controller_best(ManagedProcess*a,size_t n,uid_t uid,pid_t self,ManagedProcess**best){*best=NULL;for(size_t i=0;i<n;i++){ProcessInfo p;if(a[i].info.pid==self||a[i].info.pid==1||a[i].classification!=PROCESS_BACKGROUND||a[i].protected_flag||process_identity_valid(&a[i],&p)==0||!process_is_owned(&p,uid))continue;if(!*best||p.recent_cpu_percent>(*best)->info.recent_cpu_percent){a[i].info=p;*best=&a[i];}}return *best?0:-1;}
static int do_renice(ManagedProcess*m,const AutoNicerConfig*c,int dry,const char*log,double cpu){ProcessInfo p;int old,new;if(!process_identity_valid(m,&p))return -1;errno=0;old=getpriority(PRIO_PROCESS,m->info.pid);if(errno)return -1;new=old+c->nice_step;if(new>c->max_nice)new=c->max_nice;if(new<=old)return 1;if(dry){printf("[DRY RUN] Would renice PID %d from %d to %d.\n",m->info.pid,old,new);return 0;}if(setpriority(PRIO_PROCESS,m->info.pid,new)){logger_write(log,cpu,m->info.pid,p.name,"NICE",old,new,0,strerror(errno));return -1;}if(!m->priority_changed)m->original_nice=old;m->last_nice=new;m->priority_changed=1;m->last_action=time(NULL);logger_write(log,cpu,m->info.pid,p.name,"NICE",old,new,1,"");printf("ACTION: PID %d nice %d -> %d\n",m->info.pid,old,new);return 0;}
static void consider_pause(ManagedProcess*m,const AutoNicerConfig*c,int dry,const char*log,double cpu){ProcessInfo p;char answer[8];if(dry){printf("[DRY RUN] Would request permission to pause PID %d.\n",m->info.pid);return;}if(!c->allow_auto_pause){printf("Recommendation: pause PID %d only after user confirmation.\n",m->info.pid);return;}if(!isatty(STDIN_FILENO)){printf("Recommendation: pause PID %d (non-interactive mode).\n",m->info.pid);return;}printf("CPU remains critically high. Pause PID %d temporarily? [y/N] ",m->info.pid);fflush(stdout);if(!fgets(answer,sizeof answer,stdin)||(answer[0]!='y'&&answer[0]!='Y'))return;if(!process_identity_valid(m,&p)){puts("Pause refused: process identity changed.");return;}if(kill(m->info.pid,SIGSTOP)){logger_write(log,cpu,m->info.pid,p.name,"SIGSTOP",m->last_nice,m->last_nice,0,strerror(errno));printf("Pause failed: %s\n",strerror(errno));return;}m->paused_by_autonicer=1;m->last_action=time(NULL);logger_write(log,cpu,m->info.pid,p.name,"SIGSTOP",m->last_nice,m->last_nice,1,"");printf("ACTION: PID %d paused by AutoNicer.\n",m->info.pid);}
int controller_monitor(AutoNicerConfig*c,ManagedProcess*a,size_t n,int dry,const char*log){SystemSample prev,cur;int high=0;if(monitor_read(&prev))return -1;for(;;){sleep(c->sample_interval);if(monitor_sample(&prev,&cur))continue;prev=cur;LoadState state=cur.utilization>=c->critical_threshold?LOAD_CRITICAL:cur.utilization>=c->high_threshold?LOAD_HIGH:LOAD_NORMAL;printf("CPU: %.1f%% State: %s\n",cur.utilization,state==LOAD_CRITICAL?"CRITICAL":state==LOAD_HIGH?"HIGH":"NORMAL");for(size_t i=0;i<n;i++){ProcessInfo p;if(process_read(a[i].info.pid,&p)==0)process_update_cpu(&a[i],&p,c->sample_interval);}if(state==LOAD_HIGH||state==LOAD_CRITICAL)high++;else high=0;if(high>=c->high_samples_required&&state!=LOAD_NORMAL){ManagedProcess*b;if(controller_best(a,n,getuid(),getpid(),&b)){printf("High CPU detected, but no eligible background process is available.\n");high=0;continue;}if(time(NULL)-b->last_action<c->cooldown_seconds)continue;int action=do_renice(b,c,dry,log,cur.utilization);if(action<0)printf("Unable to modify PID %d safely.\n",b->info.pid);else if(action==1&&state==LOAD_CRITICAL&&b->priority_changed&&!b->paused_by_autonicer)consider_pause(b,c,dry,log,cur.utilization);high=0;}fflush(stdout);}}
